

# base_dir: '/mnt/win/UMoncton/Doctorat/data/acoustic/reference/CityNet/'
# root_dirs:
#   - '/mnt/win/UMoncton/Doctorat/data/dl_training/citynet/CityNet'
#   - '/mnt/win/UMoncton/Doctorat/data/dl_training/citynet/Arctic'
# train_dir: 'train'
# test_dir:  'test'
# audio_dir: 'wavs'
# annotations_dir: 'annotations'
# dest_dir: 'extracted'
# model_dir: '/mnt/win/UMoncton/Doctorat/dev/ecosongs/src/test/citynet2/models/'


data:
  # All path can be relative to the root_dir or complete
  audio_dir: 'wavs'
  tags_dir: 'annotations'
  training_dir: 'training'
  validation_dir:  'validation'
  dest_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/datasets'
  save_intermediate: False
  databases:
    # All options found in data can be overriden in each iteration. If not found, default values
    # from data will be used
    # - name: 'citynet'
    #   root_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/citynet/CityNet'
    - name: 'arctic'
      root_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/citynet/Arctic'
      overwrite: False
      # train_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/Arctic'
      # audio_dir: 'audio'
      # tags_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/Arctic2/tags'

spectrogram:
  type: "mel"
  n_mels: 32

class_type: "biotic"

model:
  model_dir: '/mnt/win/UMoncton/Doctorat/dev/dlbd/results/models/'

overwrite: True
# Spectrogram options
spec_type: 'mel'
ensemble_members: 1
HWW_X: 10
HWW_Y: 10
hww_x: 10
hww_y: 10
spec_height: 32
learn_log: 0
do_augmentation: 1
# network parameters
channels: 4
do_batch_norm: 1
num_filters: 128
num_dense_units: 512
conv_filter_width: 4
wiggle_room: 5
max_epochs: 5
learning_rate: 0.001
dropout: 0.5
classname: 'biotic'
run_type: 'test_citynet'
validation_split: 0.3
A: 0.001 # biotic 
B: 10.0 #biotic
# A: 0.025 # anthropic
# B: 2.0 # anthropic
DO_BATCH_NORM: 1
NUM_FILTERS: 128
NUM_DENSE_UNITS: 512
CONV_FILTER_WIDTH: 4
WIGGLE_ROOM: 5
LEARN_LOG: 0